[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "idsideseo"
version = "1.0.0"
description = "IdsideSEO AI Content Generation Application"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools]
py-modules = []

